---
- hosts: nodes
  tasks:
          - name: Install IB support, test deps and parser deps
            yum:
                    name: "{{ item }}"
                    state: present
            with_items:
                    - wget
                    - rsync
                    - perftest
                    - numactl

          - name: Check if mpitests is installed
            yum:
                    name: mpitests-openmpi3
                    state: present
            register: mpitests_installed
            ignore_errors: yes
            when: do_mpitest

          - name: Install mpitests
            shell: "wget {{ mpitests_rpm_url }} ; rpm -i --nodeps {{ mpitests_rpm }}"
            when: 
                - do_mpitest == true
                - mpitests_installed.rc != 0

- hosts: target
  tasks:
          - name: Get the perftest script to the target
            template:
                    src: ./templates/perftest.sh.j2
                    dest: ./perftest.sh
                    owner: root
                    group: root
                    mode: 0700
            when: do_perftest

          - name: Run the perftest
            shell: "./perftest.sh"
            when: do_perftest

          - name: Get the mpi perftest script to the target
            template:
                    src: ./templates/mpi_perftest.sh.j2
                    dest: ./mpi_perftest.sh
                    owner: root
                    group: root
                    mode: 0700
            when: do_mpitest

          - name: Run the MPI tests
            shell: "./mpi_perftest.sh"
            when: do_mpitest

          - name: Find results
            find:
              paths: "./"
              patterns: "log-{{ item.name }}-{{ results_tag }}.txt"
            register: results_path
            failed_when: results_path.matched == 0
            with_items:
                    - "{{ tests }}"
          - debug: var=results_path

          - name: Move the results back for them to be converted to xml
            fetch:
                     src: "{{ item.files[0].path }}"
                     dest: "{{ playbook_dir }}/"
                     flat: yes
            with_items:
                    - "{{ results_path.results }}"

          - name: Parse ib_write_bw test output and produces an JUnit/XUnit xml file (see README.md for options)
            test_result_parser:
                    test_output_path: "{{ playbook_dir }}/log-{{ item.name }}-{{ results_tag }}.txt"
                    test_threshold: "{{ item.threshold }}"
                    junit_write_path: "{{ workspace }}/results"
                    tag: "{{ results_tag }}"
            delegate_to: localhost-py3
            with_items:
                    - "{{ tests }}"
